# Generated by Django 3.1.7 on 2021-03-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210321_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='savePrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='discountPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
