# Generated by Django 3.1.7 on 2021-03-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210324_2055'),
        ('store', '0009_orderitem_status'),
    ]

    operations = [
    ]
