# Generated by Django 3.1.7 on 2021-03-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210328_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='conf_password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
