# Generated by Django 3.1.7 on 2021-03-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_customer_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
