# Generated by Django 3.1.7 on 2021-03-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210329_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_img',
        ),
    ]
