# Generated by Django 3.1.7 on 2021-04-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
